@startuml
'https://plantuml.com/class-diagram

class App
class ListController
class listManager
class list
class item


javafx.Assignment4 <|-- App

App -- ListController
App -- listManager
App -- list
App -- item

listManager -- list
listManager -- item

list -- item

class App {
main(String [] args) : void
start(Stage primaryStage) : void
}

class listManager {
todoLists : HashMap<String, ArrayList<item>>
currentList : ArrayList<item>

getTodo(String name) : ArrayList<item>
getMap() : HashMap<String, ArrayList<item>>
addTodo(String name) : void
removeList(String name) : void
editList(String nameOld, String nameNew) : void
saveListAll(ArrayList<item>, String name) : void
loadList(String file) : void
}

class list {
getItem(String number, ArrayList<item> list) : item
displayAll(ArrayList<item> list) : String
displayIncomplete(ArrayList<item> list) : String
displayComplete(ArrayList<item> list) : String
saveList(ArrayList<item>, String name) : void
addItem(ArrayList<item> list) : void
removeItem(ArrayList<item>, String name) : void
}

class item {
- description : String
- dueDate : String
- status : String

editDescription(String newDescription) : void
editDate(String newDate) : void
completion() : void
}

class ListController {
- textArea: TextArea

userInputEntered() : String
textAreaScroll() : void
addListClick() : void
removeListClick() : void
saveAllClick() : void
editListClick() : void
addItemClick() : void
printCompClick() : void
saveListClick() : void
removeItemClick() : void
printIncompClick() : void
editItemClick() : void
completeItemClick() : void
printAllClick() : void
}
@enduml